source "https://rubygems.org"

gem "rails", "4.2.3"
gem "bootstrap-sass"
gem "bootstrap-datepicker-rails"
gem "mysql2"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "twitter-bootstrap-rails", ">= 2.0.3"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "rails_config"
gem "sdoc", "~> 0.4.0", group: :doc
gem "jquery-turbolinks"
gem "devise"
gem "cancancan"
gem "config"
gem "rails_admin", github: "sferik/rails_admin"
gem "rails_admin_map_field", git: "https://github.com/HieuMeo/RailsAdminMapField.git"
gem "rails_admin_nestable"

group :development, :test do
  gem "pry"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "faker"
  gem "factory_girl_rails"
  gem "i18n-tasks"
  gem "rspec-rails"
end

