source "https://rubygems.org"

gem "rails", "4.2.3"
gem "bootstrap-sass"
gem "mysql2", "~> 0.3.13"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "config"
gem "sdoc", "~> 0.4.0", group: :doc
gem "jquery-turbolinks"
gem "devise"
gem "cancancan"
gem "ransack"
gem "font-awesome-rails"
gem "rails_admin"
gem "rails_admin_import", "~> 1.2"
gem "unicorn", "~> 5.0.1"
gem "metamagic"
gem "sitemap_generator"
gem "carrierwave"
gem "actionpack-page_caching"
gem "hover-rails"
gem "curb"
gem "mechanize"
gem "sidekiq"
gem "google-api-client"
gem "sinatra", require: false
gem "capybara-webkit"
gem "capybara"
gem "selenium-webdriver"
gem "headless"
gem "sinatra", require: false
gem "resque-pool"
gem "resque", require: "resque/server"
gem "htmlcompressor"

group :development, :test do
  gem "pry"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "faker"
  gem "factory_girl_rails"
  gem "rspec-rails"
end
