roles:
  admin: 1
  normal: 0
category:
  name:
    maximum: 30
movie:
  title:
    maximum: 40
  slide: 10
  description:
    maximum: 300
  hd: "hd"
  sd: "sd"
review:
  review:
    maximum: 200
comment:
  comment:
    maximum: 200
request:
  name:
    maximum: 200
  description:
    maximum: 300
images:
  default:
    - /app/assets/images/default_movie_1.png
    - /app/assets/images/default_movie_2.png
    - /app/assets/images/default_movie_3.png
  stream:
    hd: //c1.staticflickr.com/1/771/21563498225_3c8b33449e_t.jpg
    sd: //c2.staticflickr.com/6/5814/22779052009_4cf902902f_m.jpg
  status:
    is_main: 1
    not_main: 0
page:
  per_page_movie: 20
status_progress:
  start: 0
  doing: 1
  failed: 2
  finished: 3
remaining_time:
  fnished: 0
